[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
/(
  \.toml
  |\.sh
  |\.git
  |\.ini
  |\.ipynb
  |\.log
  |.vscode
  |Dockerfile
  |data
  |debug
)/
'''