DEVICE: [0]
TENSORBOARD_DIR: data/tensorboard_dirs/vit_small
CHECKPOINT_DIR: data/checkpoints/vit_small
TRAINER:
  batch_size: 128
  epochs: 1
  adam_epsilon: 1e-8
  weight_decay: 1e-3
  learning_rate: 2e-5
MODEL:
  loss_type: TAC
  bottleneck: vits
  init_time_scale: 0.083333333333333333333333333333333
  load_from_ckpt: True
  ckpt_path: data/checkpoints/vit_small/step/ckpt.TAC.160000.pth
  DEPTH:
    trainable: True
    feature_dim: 512
DATA:
  RGBD:
    block_size: 8