DEVICE: [0]
TENSORBOARD_DIR: data/tensorboard_dirs/tacv2_mae
CHECKPOINT_DIR: data/checkpoints/tacv2_mae
TRAINER:
  batch_size: 128
  epochs: 1
MODEL:
  name: MAE
  loss_type: RGB2DEPTH
  IMAGE:
    model_name: /root/TAC/data/checkpoints/maeRGB2DEPTH
    trainable: False
  DEPTH:
    model_name: /root/TAC/data/checkpoints/maeDEPTH2RGB
    trainable: False