DEVICE: [0]
TENSORBOARD_DIR: data/tensorboard_dirs/v2_tac_multilabel
CHECKPOINT_DIR: data/checkpoints/v2_tac_multilabel
TRAINER:
  batch_size: 128
  epochs: 1
  adam_epsilon: 1e-8
  weight_decay: 1e-3
  learning_rate: 2e-5
MODEL:
  loss_type: MULI_LABEL
  init_time_scale: 0.083333333333333333333333333333333
  bottleneck: vit
  load_from_ckpt: True
  ckpt_path: data/checkpoints/v2_tac_multilabel/step/ckpt.TAC.160000.pth
  IMAGE:
    model_name: openai/clip-vit-base-patch32
    trainable: True
DATA:
  RGBD:
    block_size: 8
    